on: push
jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - name: curl
      uses: wei/curl@master
      with:
        args: -o /home/runner/work/Myprofile/Myprofile/1.txt https://httpbin.org/get
